name: Publish TestPyPI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-tags: true
          fetch-depth: 0
          ref: main
          token: ${{ steps.app-token.outputs.token }} # Needed to trigger other actions

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Get Latest Release Version
        id: get_release
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest release version: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV # Save the tag to an environment variable

      - name: Create .pypirc file
        run: |
          echo "[test]" > ~/.pypirc
          echo "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
          echo "username = __token__" >> ~/.pypirc
          echo "password = ${{ secrets.TEST_PYPI_API_TOKEN }}" >> ~/.pypirc
          chmod 600 ~/.pypirc

      - name: Publish to TestPyPI
        run: |
          hatch build
          hatch publish --repo test
